[build-system]
requires = ["setuptools>=45", "wheel", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[project]
name = "praisonaippt"
version = "1.0.0"
description = "PraisonAI PPT - Create beautiful PowerPoint presentations from Bible verses in JSON format"
readme = "README.md"
requires-python = ">=3.7"
license = "MIT"
authors = [
    {name = "MervinPraison"}
]
keywords = ["powerpoint", "pptx", "bible", "verses", "presentation", "generator", "praisonai"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: End Users/Desktop",
    "Topic :: Religion",
    "Topic :: Office/Business :: Office Suites",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
dependencies = [
    "python-pptx>=0.6.21",
]

[project.urls]
Homepage = "https://github.com/MervinPraison/PraisonAIPPT"
"Bug Reports" = "https://github.com/MervinPraison/PraisonAIPPT/issues"
"Source" = "https://github.com/MervinPraison/PraisonAIPPT"

[project.scripts]
praisonaippt = "praisonaippt.cli:main"

[tool.setuptools]
packages = ["praisonaippt"]

[tool.setuptools.package-data]
"*" = ["examples/*.json"]
